# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

title: MCP Traffic - Tokyo Traffic Data Collection
email: contact@mcp-traffic.example.com
description: >-
  A comprehensive Tokyo traffic data collection and analysis system.
  Real-time monitoring, data visualization, and historical analysis
  of traffic patterns using the ODPT (Open Data Platform for Transportation) API.

baseurl: ""
url: "https://tatsuru-kikuchi.github.io/MCP-traffic"
github_username: Tatsuru-Kikuchi

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - logs/
  - data/
  - src/
  - scripts/
  - config/
  - requirements.txt
  - .bundle/
  - venv/
  - __pycache__/
  - "*.pyc"
  - README.md
  - LICENSE
  - Dockerfile
  - docker-compose.yml
  - "*.yml"

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Navigation
header_pages:
  - about.md
  - docs/index.md
  - contact.md

# Author information
author:
  name: Tatsuru Kikuchi
  email: contact@mcp-traffic.example.com

# Minima theme settings
minima:
  social_links:
    github: Tatsuru-Kikuchi
